spring:
  application:
    name: JavaBootAdmin
  # 增加后台
  security:
    user:
      name: "admin"
      password: "admin"
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: 3360739100@qq.com
    password: udjthezlfwcschdh
    properties:
        mail.smtp.auth: true # 启用SMTP认证
        mail.smtp.starttls.enabled: true # 启用SMTP认证
        mail.smtp.starttls.required: true # 必须采用加密链接
server:
  port: 9999

