spring:
  application:
    name: @artifactId@
  main:
    allow-circular-references: true
  # 增加后台登录配置
  security:
    user:
      name: @admin.username@
      password: @admin.username@
server:
  port: 9999


